#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Result
  include ::Thrift::Struct, ::Thrift::Struct_Union
  STATUS = 1
  CONTENT = 2

  FIELDS = {
    STATUS => {:type => ::Thrift::Types::I32, :name => 'status'},
    CONTENT => {:type => ::Thrift::Types::STRING, :name => 'content'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

